name: Release & Maybe Push Production

on:
  push:
    branches:
      - main
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
      sha: ${{ steps.release.outputs.sha }}
    steps:
      - name: Release
        id: release
        uses: google-github-actions/release-please-action@v3.1.2
        with:
          release-type: simple
          version-file: version.txt
          extra-files: |
            README.md

  push-production:
    runs-on: ubuntu-latest
    needs: release
    if: ${{needs.release.outputs.release_created}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Push to Production Branch 
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: production
          force: true
          directory: .
