# This is a basic workflow to help you get started with Actions

name: Build & Release

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
    paths-ignore:
      - "CHANGELOG.md"
      - "README.md"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
      sha: ${{ steps.release.outputs.sha }}
    steps:
      - name: Release
        id: release
        uses: google-github-actions/release-please-action@v3.1.2
        with:
          release-type: simple
          version-file: version.txt
          extra-files: |
            README.md
  build:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 16
          cache: 'yarn'
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install Dependencies
        run: yarn --frozen-lockfile --prod
      - name: Build
        run: yarn build
      - name: Push Build [Development]
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          commit-message: Build v${{needs.release.outputs.version}}-${{needs.release.outputs.sha}}
          source-directory: build
          destination-github-username: smleaks
          destination-repository-name: website-new-development
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
          target-branch: main
      - name: Push Build [Production]
        uses: cpina/github-action-push-to-another-repository@main
        if: ${{needs.release.outputs.release_created}}
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          commit-message: Build v${{needs.release.outputs.version}}-${{needs.release.outputs.sha}}
          source-directory: build
          destination-github-username: smleaks
          destination-repository-name: website-new-production
          user-email: 41898282+github-actions[bot]@users.noreply.github.com
          target-branch: main
