# This is a basic workflow to help you get started with Actions

name: Build & Release

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      version: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}
      sha: ${{ steps.release.outputs.sha }}
    steps:
      - name: Release
        id: release
        uses: google-github-actions/release-please-action@v3.1.2
        with:
          release-type: simple
          version-file: version.txt
          extra-files: |
            README.md
  build:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: mstachniuk/ci-skip@v1
        with:
          fail-fast: true
      - name: Setup NodeJS 16
        uses: actions/setup-node@v3.1.0
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn --frozen-lockfile --prod
      - name: Build
        run: yarn build
      - name: Upload Development Build
        uses: actions/upload-artifact@v3.0.0
        with:
          name: development-build-v${{needs.release.outputs.version}}-${{needs.release.outputs.sha}}.zip
          path: build/
      - name: Upload Production Build
        uses: actions/upload-artifact@v3.0.0
        if: ${{needs.release.outputs.release_created}}
        with:
          name: production-build-v${{needs.release.outputs.version}}.zip
          path: build/
